INSERT INTO book(title, author) VALUES('To Kill a Mockingbird', 'Harper Lee');
INSERT INTO book(title, author) VALUES('In Search of Lost Time', 'Marcel Proust');
INSERT INTO book(title, author) VALUES('Ulysses', 'James Joyce');
INSERT INTO book(title, author) VALUES('Don Quixote', 'Miguel de Cervantes');
INSERT INTO book(title, author) VALUES('One Hundred Years of Solitude', 'Gabriel Garcia Marquez');
INSERT INTO book(title, author) VALUES('The Great Gatsby','F.Scott Fitzgerald');
INSERT INTO book(title, author) VALUES('War and Peace','Leo Tolstoy');
INSERT INTO book(title, author) VALUES('War and Peace','Leo Tolstoy');
INSERT INTO book(title, author) VALUES('Hamlet','William Shakespeare');
INSERT INTO book(title, author) VALUES('The Odyssey','Homer');
INSERT INTO book(title, author) VALUES('Madame Bovary','Gustave Flaubert');
INSERT INTO book(title, author) VALUES('The Divine Comedy','Dante Alighieri');